scopes:
  files:
    github:
      includes:
        - .github/**/*
    action:
      includes:
        - action.yml
    other:
      includes:
        - "**/*"
      excludes:
        - action.yml
        - .github/**/*
