extends: .github
shared:
  IsPublicHolidays: &IsPublicHolidays
    or:
      - current-datetime = XXXX-01-01T00:00/XXXX-01-01T23:59[Europe/Paris]
      - current-datetime = XXXX-05-01T00:00/XXXX-05-01T23:59[Europe/Paris]
      - current-datetime = XXXX-05-08T00:00/XXXX-05-08T23:59[Europe/Paris]
      - current-datetime = XXXX-07-14T00:00/XXXX-07-14T23:59[Europe/Paris]
      - current-datetime = XXXX-08-15T00:00/XXXX-08-15T23:59[Europe/Paris]
      - current-datetime = XXXX-11-01T00:00/XXXX-11-01T23:59[Europe/Paris]
      - current-datetime = XXXX-11-11T00:00/XXXX-11-11T23:59[Europe/Paris]
      - current-datetime = XXXX-12-25T00:00/XXXX-12-25T23:59[Europe/Paris]
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash
  CheckRuns: &CheckRuns
    - check-success=linters
    - check-success=actions
    - check-success=test

queue_rules:
  - name: default
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base=main
      - and: *CheckRuns
      - or: &DefaultReviewCond
          - "#approved-reviews-by>=1"
          - and:
              - author=mergify-ci-bot
              - head=trivy/daily-report
              - approved-reviews-by=@eng-mgr
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - "#review-requested=0"
    merge_conditions:
      - and: *CheckRuns
      - and:
          - not: *IsPublicHolidays
          - schedule=Mon-Fri 09:00-17:30[Europe/Paris]

  - name: lowprio
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base=main
      - and: *CheckRuns
      - "#commits=1"
      - or:
          - and:
              - author=mergify-ci-bot
              - head~=^clifus/
              - "title~=^chore: bump"
          - and:
              - author=mergify-ci-bot
              - head=trivy/daily-report
              - label!=new CVE
          - and:
              - author=mergify-ci-bot
              - head=openapi-spec-sync
          - author=dependabot[bot]
    merge_method: merge
    merge_conditions:
      - and: *CheckRuns
      - and:
          - not: *IsPublicHolidays
          - schedule=Mon-Fri 09:00-17:00[Europe/Paris]
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
    queue_branch_merge_method: fast-forward

pull_request_rules:
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - and: *CheckRuns
      - "#changes-requested-reviews-by=0"
      - review-requested!=@devs
      - not:
         or: *DefaultReviewCond
    actions:
      request_reviews:
        teams:
          - devs
