name: 'mergify-merge-queue-base-sha'
description: 'Mergify: retrieve the base sha the CI should used to detect changed files'
branding:
  icon: arrow-up
  color: 'blue'
outputs:
  checking_base_sha:
    description: 'The base SHA that CI should use to detect changed files'
    value: ${{ steps.extract-base-sha.outputs.checking_base_sha }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      shell: bash
      run: echo "$GITHUB_ACTION_PATH" >> "$GITHUB_PATH"

    - name: Get checking base sha
      id: extract-base-sha
      shell: bash
      if: startsWith(github.head_ref, 'mergify/merge-queue/')
      env:
        REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
        MERGE_QUEUE_PR_URL: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
      run: run.sh
