name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - devs/**

jobs:
  linters:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5.0.0

      - name: Actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5.0.0
      - name: Trying action
        uses: ./.
